name: mobile_client_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  provider: ^6.0.5
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  image_picker: ^1.0.7
  flutter_animate: ^4.5.0
  glassmorphism: ^3.0.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  uuid: ^4.3.3
  # Voice-related packages
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  permission_handler: ^10.4.5
  audio_session: ^0.1.18
  just_audio: ^0.9.36
  vapi: ^0.0.9
  google_maps_flutter: ^2.10.1

  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/doormate-logo.png
    - assets/images/google-logo.png
    - assets/animations/