version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/doormate
      - DATABASE_NAME=doormate
      - JWT_SECRET=your_secret_key_here
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - MAIL_USERNAME=doormate@example.com
      - MAIL_PASSWORD=password123
      - MAIL_SERVER=smtp.example.com
      - MAIL_FROM=doormate@example.com
      - MAIL_PORT=587
      - MAIL_TLS=True
      - MAIL_SSL=False
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: